### ISSUE TITLE
Update JS form event triggers since on_sent_ok/on_submit have been deprecated

### ISSUE THREAD

**Issue by KZeni** [kasparsd/contact-form-7-extras#10]
https://contactform7.com/additional-settings/#javascript shows that the developer of Contact Form 7 is planning to drop support of on_sent_ok/OnSentOk and on_submit/OnSubmit by EOY 2017.

The successful page redirect and Google Analytics event trigger features both rely on the use of these deprecated commands and will therefore break as soon as the version which removes this is released. I'm not sure if any other features use this, but those are two I know of.

It would be best to rewrite these features so they no longer use on_sent_ok/OnSentOk or on_submit/OnSubmit sooner than later.

I have also posted this on the WordPress.org support forum at: https://wordpress.org/support/topic/redirection-analytics-event-features-rely-on-deprecated-cf7-functionality/

**Comment by ctadlock** [comment]
What is the status of this?

**Comment by kasparsd** [comment]
I guess the solution is to add support for the suggested [events](https://contactform7.com/tracking-form-submissions-with-google-analytics/):

```
document.addEventListener( 'wpcf7mailsent', function( event ) {
    ga( 'send', 'event', 'Contact Form', 'submit' );
}, false );
```

I'm not sure how to best support both the legacy tracking and this new event based approach.

**Comment by KZeni** [comment]
I've suggested that the CF7 developer have a more lenient migration period (mentioned in my comment here: https://wordpress.org/support/topic/version-4-8-dev-update/#post-9115095 ), but I haven't heard back & the documentation says the old method will be removed EOY 2017.

I see CF7 has `define( 'WPCF7_VERSION', '4.8' );` in it's main `wp-contact-form-7.php` file. Couldn't this plugin be updated to pull this constant and see if the value is lower than the version where the new behavior was added and then change the code based on this condition. Example: `if(( WPCF7_VERSION + 0 )<4.7){$use_old_js_event_method = true;}` or something to this effect. That way, you can have the on_sent_ok/OnSentOk and on_submit/OnSubmit methods used if $use_old_js_event_method === true while you use the newer document.addEventListener setup if $use_old_js_event_method === false when appropriate.

I mean, they'd need to update their CF7 plugin to have this be an issue. Can't we assume they'd also update the CF7 Controls plugin where the version check was patched in and vice-versa?

**Comment by Jeppeskovsgaard** [comment]
Any updates?
