### ISSUE TITLE
Remove languages directory to allow community translations

### ISSUE THREAD

**Issue by kasparsd** [kasparsd/contact-form-7-extras#19]
See https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain

> After WordPress 4.6 came out, translations now take translate.wordpress.org as priority and so plugins that are translated via translate.wordpress.org do not necessary require load_plugin_textdomain() anymore.
If you don’t want to add a load_plugin_textdomain() call to your plugin you have to set the Requires at least: field in your readme.txt to 4.6.

**Comment by buzztone** [comment]
Text Domain needs to match exactly WP.org plugin url to get loaded onto translate.wordpress.org

- **Current** - Text Domain: cf7-extras
- **Should be** - Text Domain: contact-form-7-extras

**Comment by kasparsd** [comment]
Indeed @buzztone:

> For a plugin to be imported properly and take advantage of language packs, it must have a text domain that matches its slug (e.g., a plugin with the “akismet” slug must have a text domain of “akismet”) and must not have more than one text domain.

from https://make.wordpress.org/meta/handbook/documentation/translations/
