### ISSUE TITLE
Event Tracking seems not working

### ISSUE THREAD

**Issue by aicompgroup** [kasparsd/contact-form-7-extras#25]
Are there any know issues? I have enabled the event tracking and have sent mails but don't get any signal in Google Analytics?

Any idea wht's wrong there?

**Comment by kasparsd** [comment]
Thanks for reporting the issue @aicompgroup!

Can you please paste in the GA tracking script you have installed on your site (please replace the site ID)? Is it using the [latest tracking code version](https://support.google.com/analytics/answer/7538414) of the legacy [analytics.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/)?
